
import ClientOnly from './Clientonly';

import './globals.css'
import { Inter } from 'next/font/google';
import Navbar from './Navbar/Navbar';
import Searchhistory from './Navbar/components/modal/Searchhistory';
import AppContextProvider from '@/context/AppContext';
import { AuthProvider } from './Providers';
import Sidebar from './Navbar/sidebar/Sidebar';
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import ReduxStoreProvider from '@/store/provider';
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dar'>
      <body className={inter.className}>
        <ClientOnly>
        <AuthProvider>
          <ReduxStoreProvider>
          <AppContextProvider>         
          <div className="is-header-blur " id='mydiv'>
            <div
              id="root"
              className="min-h-100vh flex grow bg-slate-50 dark:bg-navy-900"
            >
              <Sidebar/>
              <nav className="header before:bg-white dark:before:bg-navy-750 print:hidden">
                <Navbar/>
              </nav>
              <Searchhistory/>
              {children}
              <ToastContainer />
            </div>
          </div>
          
          </AppContextProvider>
          </ReduxStoreProvider>
          </AuthProvider>
        </ClientOnly>

      </body>
    </html >
  )
}
