import Header from '@/components/header/Header';
import AppContextProvider from '@/context/AppContext';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className=''>
            <body>
            <AppContextProvider>
          <div className="is-header-blur">
            <div
              id="root"
              className="min-h-100vh flex grow bg-slate-50 dark:bg-navy-900"
            >
              {/* All Sidebar */}
              {/* <Sidebar /> */}

              {/* App Header Wrapper */}
              <nav className="header before:bg-white dark:before:bg-navy-750 print:hidden">
                <Header />
              </nav>
                
              {/* <!-- Mobile Searchbar --> */}
              {/* <MobileSearchBar /> */}
              {/* This is Main Page */}
              {children}
           
              
              {/* <ToastContainer /> */}
            </div>
          </div>
      
          </AppContextProvider>
                    </body>
                </html >
                )
}
